### ISSUE TITLE
```@truthtable``` macro docstring broken in REPL

### ISSUE THREAD

**Issue by ErikQQY** [eliascarv/TruthTables.jl#15]
Hello, this package is really interesting :)

When I was using the ```@truthtable``` macro and check the docstrings for it:

```julia
help?>@truthtable
```
There are some errors:
```julia
help?> @truthtable
  @truthtable formula [full=false]


  Creates a truth table for the logical propositional formula.

  full is an optional keyword argument which by default is false. If full is true, the truth table will be
  created in expanded form.

  List of logical operators
  ===========================

    •  AND: &&, &, ∧ (\wedge<tab>)

    •  OR: ||, |, ∨ (\vee<tab>)

    •  NOT: !, ~, ¬ (\neg<tab>)

    •  XOR: ⊻ (\xor<tab>)

    •  NAND: ⊼ (\nand<tab>)

    •  NOR: ⊽ (\nor<tab>)

    •  IMPLICATION: -->

    •  EQUIVALENCE: <-->, ≡ (\equiv<tab>)

  Examples
  ≡≡≡≡≡≡≡≡≡≡

Error showing value of type Markdown.MD:
ERROR: KeyError: key Tokenize.Tokens.DOUBLE_ARROW not found
Stacktrace:
  [1] getindex
    @ .\dict.jl:482 [inlined]
  [2] untokenize(t::Tokenize.Tokens.Token)
.............
```

**Comment by eliascarv** [comment]
This is strange, on my PC this error does not occur.
What version of Julia are you using? 
What operating system do you use?

**Comment by eliascarv** [comment]
Are you using OhMyREPL.jl @ErikQQY?

**Comment by ErikQQY** [comment]
Yeah, I am using OhMyREPL.jl, Windows11 terminal Julia 1.6.1🤔

**Comment by eliascarv** [comment]
What version of OhMyREPL.jl are you using?

**Comment by ErikQQY** [comment]
Sorry for the late response, I am using OhMyREPL v0.5.12

**Comment by eliascarv** [comment]
This is weird, I tried running this code on Windows 10 and Ubuntu and it didn't throw an error.

**Comment by eliascarv** [comment]
I have a hunch. Could you run this code for me to check it:
```julia
julia> using OhMyREPL

julia> using OhMyREPL.Tokenize

julia> Tokenize.Tokens.DOUBLE_ARROW 
DOUBLE_ARROW::Kind = 109
```

**Comment by ErikQQY** [comment]
I run this code in the REPL:

![screen](https://user-images.githubusercontent.com/52615090/168462720-64ba1827-1823-485a-97aa-ebb5de481b29.png)

**Comment by eliascarv** [comment]
OK, another test, run this code:
```julia
julia> using OhMyREPL

julia> using OhMyREPL.Tokenize

julia> Tokenize.Tokens.isoperator(Tokenize.Tokens.DOUBLE_ARROW)
true

julia> Tokenize.Tokens.UNICODE_OPS_REVERSE[Tokenize.Tokens.DOUBLE_ARROW]
:<-->
```

**Comment by ErikQQY** [comment]
That errors:

```julia
julia> using OhMyREPL

julia> using OhMyREPL.Tokenize

julia> Tokenize.Tokens.isoperator(Tokenize.Tokens.DOUBLE_ARROW)
true

julia> Tokenize.Tokens.UNICODE_OPS_REVERSE[Tokenize.Tokens.DOUBLE_ARROW]
ERROR: KeyError: key Tokenize.Tokens.DOUBLE_ARROW not found
Stacktrace:
 [1] getindex(h::Dict{Tokenize.Tokens.Kind, Symbol}, key::Tokenize.Tokens.Kind)
   @ Base .\dict.jl:482
 [2] top-level scope
   @ REPL[4]:1
```

**Comment by eliascarv** [comment]
This is the error! 
This bug has been fixed in the latest version of Tokenize.
Run:
```julia
julia>] up
```
To update all packages and dependencies.

**Comment by ErikQQY** [comment]
Wow!! After I update, the error has gone! Thanks a lot!!!!

**Comment by eliascarv** [comment]
You are welcome!
What is your opinion about TruthTables.jl? Suggestions are welcome!

**Comment by ErikQQY** [comment]
This package is pretty useful, I am learning logic, so when I need to see the result, I just use the ```@truthtable``` macro, also the output is quite beautiful.😉

As for some improvement, I think adding more elaborating error messages would be nice, for example, when I accidentally input the wrong expression, I wish the program can tell me I made a mistake instead of 

```julia
ERROR: MethodError: no method matching TruthTables.TruthTable(::Vector{Vector{Int64}}, ::Vector{Symbol})
Closest candidates are:
......
```

I think that would also be easier for those new Julia learners.

**Comment by eliascarv** [comment]
Thanks for the suggestion.
Is the expression you inputed something like this?
```julia
@truthtable p + q
```

**Comment by ErikQQY** [comment]
Yeah, I think the wrong input like that should have a more elaborated error message:)

**Comment by eliascarv** [comment]
The last release comes with better error messages:
```julia
julia> using TruthTables

julia> @truthtable p + q
ERROR: LoadError: ArgumentError: Expression with invalid operator.
Stacktrace:
...
```

**Comment by ErikQQY** [comment]
Great works!!😄
